/lidar_centerpoint:
  ros__parameters:
    allow_remapping_by_area_matrix:
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 1
    - 0
    - 1
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 1
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 1
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    build_only: false
    cloud_capacity: 2000000
    densification_params:
      num_past_frames: 1
      world_frame_id: map
    diagnostic_updater:
      period: 1.0
      use_fqn: false
    diagnostics:
      max_acceptable_consecutive_delay_ms: 1000.0
      max_allowed_processing_time_ms: 200.0
      validation_callback_interval_ms: 100.0
    encoder_engine_path: /home/hamdy/autoware_data/lidar_centerpoint/pts_voxel_encoder_centerpoint_tiny.engine
    encoder_onnx_path: /home/hamdy/autoware_data/lidar_centerpoint/pts_voxel_encoder_centerpoint_tiny.onnx
    head_engine_path: /home/hamdy/autoware_data/lidar_centerpoint/pts_backbone_neck_head_centerpoint_tiny.engine
    head_onnx_path: /home/hamdy/autoware_data/lidar_centerpoint/pts_backbone_neck_head_centerpoint_tiny.onnx
    max_area_matrix:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 36.0
    - 0.0
    - 999.999
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 999.999
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 999.999
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    min_area_matrix:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 12.1
    - 0.0
    - 36.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 36.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 36.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    model_params:
      class_names:
      - CAR
      - TRUCK
      - BUS
      - BICYCLE
      - PEDESTRIAN
      downsample_factor: 2
      encoder_in_feature_size: 9
      has_twist: false
      has_variance: false
      max_voxel_size: 40000
      point_cloud_range:
      - -76.8
      - -76.8
      - -4.0
      - 76.8
      - 76.8
      - 6.0
      point_feature_size: 4
      voxel_size:
      - 0.32
      - 0.32
      - 10.0
    post_process_params:
      circle_nms_dist_threshold: 0.5
      iou_nms_search_distance_2d: 10.0
      iou_nms_threshold: 0.1
      score_threshold: 0.35
      yaw_norm_thresholds:
      - 0.3
      - 0.3
      - 0.3
      - 0.3
      - 0.0
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
    trt_precision: fp16
    use_sim_time: false

